# Generated by Django 4.2.7 on 2023-11-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_study_dream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
